
Category.create!(name: "Rock")
Category.create!(name: "Metal")
Category.create!(name: "Rap/Hip-Hop")
Category.create!(name: "Global")
Category.create!(name: "Experimental")
Category.create!(name: "Pop/R&B")
Category.create!(name: "Jazz")
Category.create!(name: "Folk/Country")
Category.create!(name: "Electronic")
Category.create!(name: "Rock")
